In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

``` Load Dataset```

In [2]:
df = pd.read_csv("./dataset/Train_Data.csv")
df

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1095  1096          20       RL  ...        WD         Normal    176432
1096  1097          70       RM  ...        WD         Normal    127000
1097  1098         120       RL  ...        WD         Normal    170000
1098  1099          50       RM  ...        WD         Normal    128000
1099  1100          20       RL  ...       COD        Abnorml    157000

[1100 rows x 81 columns]

## Data Cleaning

In [3]:
def is_there_null(df):
  null_values = list(df.isnull().sum())
  columns = df.columns
  null_values = {columns[i] : null_values[i] for i in range(len(columns)) if null_values[i] != 0}
  return null_values

In [4]:
null_values = is_there_null(df)
print(null_values)

{'LotFrontage': 192, 'Alley': 1031, 'MasVnrType': 6, 'MasVnrArea': 6, 'BsmtQual': 31, 'BsmtCond': 31, 'BsmtExposure': 32, 'BsmtFinType1': 31, 'BsmtFinType2': 32, 'FireplaceQu': 524, 'GarageType': 61, 'GarageYrBlt': 61, 'GarageFinish': 61, 'GarageQual': 61, 'GarageCond': 61, 'PoolQC': 1098, 'Fence': 892, 'MiscFeature': 1054}

```Droping those columns which contain maximum of null values```

In [5]:
columns_to_drop = ["Id", "Alley", "Fence", "FireplaceQu", "MiscFeature", "PoolQC"]
df.drop(columns = columns_to_drop, inplace = True)
df.head()

   MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500
1          20       RL         80.0  ...        WD        Normal    181500
2          60       RL         68.0  ...        WD        Normal    223500
3          70       RL         60.0  ...        WD       Abnorml    140000
4          60       RL         84.0  ...        WD        Normal    250000

[5 rows x 75 columns]

In [6]:
null_values = is_there_null(df)
print(null_values)

{'LotFrontage': 192, 'MasVnrType': 6, 'MasVnrArea': 6, 'BsmtQual': 31, 'BsmtCond': 31, 'BsmtExposure': 32, 'BsmtFinType1': 31, 'BsmtFinType2': 32, 'GarageType': 61, 'GarageYrBlt': 61, 'GarageFinish': 61, 'GarageQual': 61, 'GarageCond': 61}

## Filling NaN values and Label Encoding

In [7]:
for column in df.columns:
  if df[column].dtype == "object":
    df[column] = df[column].astype("category")
    df[column] = df[column].cat.codes  
  elif df[column].isnull().any():
    df[column].fillna(value = round(df[column].mean()), inplace = True)
    del null_values[column]

In [8]:
print(null_values)

{'MasVnrType': 6, 'BsmtQual': 31, 'BsmtCond': 31, 'BsmtExposure': 32, 'BsmtFinType1': 31, 'BsmtFinType2': 32, 'GarageType': 61, 'GarageFinish': 61, 'GarageQual': 61, 'GarageCond': 61}

## Label Encoders make Nan values equal to -1 So it is better to replace them with mean values

In [9]:
df.head()

   MSSubClass  MSZoning  LotFrontage  ...  SaleType  SaleCondition  SalePrice
0          60         3         65.0  ...         8              4     208500
1          20         3         80.0  ...         8              4     181500
2          60         3         68.0  ...         8              4     223500
3          70         3         60.0  ...         8              0     140000
4          60         3         84.0  ...         8              4     250000

[5 rows x 75 columns]

In [10]:
for key in null_values.keys():
  df.loc[df[key] == -1, key] = round(df[key].mean())

In [11]:
(df["MasVnrType"] == -1).any()

False